project_id = "cimjybhmilaecqhnqrby"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.guest-order-lookup]
verify_jwt = false

[functions.contact-form]
verify_jwt = false