// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cimjybhmilaecqhnqrby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpbWp5YmhtaWxhZWNxaG5xcmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODczMTgsImV4cCI6MjA3NDU2MzMxOH0.8Wu8JTvhyA2CWH2wHUHRLNpFTMIfmBZKT6Msct5sOXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});